@echo off
chcp 65001 >nul
echo Очистка промежуточных файлов...
dotnet clean -c Release
echo Удаление папки obj...
if exist obj rmdir /s /q obj
echo Восстановление зависимостей...
dotnet restore
echo Публикация проекта...
dotnet publish -r win-x64 -c Release --self-contained false --output ./publish /p:PublishSingleFile=true /p:DebugType=None
echo Готово!
pause