name: Build & Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v2

      - name: Run build script
        working-directory: ./src
        run: workflow.cmd
        shell: cmd

      - name: Extract version, prerelease flag & message
        id: extract
        run: |
          $version = Get-Content -Path src\version
          echo "version=$version" >> $GITHUB_OUTPUT

          $pr = Get-Content -Path src\prerelease
          echo "prerelease=$pr" >> $GITHUB_OUTPUT

          $title = Get-Content -Path src\title
          echo "title=$title" >> $GITHUB_OUTPUT

          $msg = Get-Content -Path src\message
          echo "body=$msg" >> $GITHUB_OUTPUT
        shell: pwsh
      - name: Delete existing ZIP asset (if any)
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.extract.outputs.version }}
          assets: DSL-KeyPad-${{ steps.extract.outputs.version }}.zip
          fail-if-no-release: false
          fail-if-no-assets: false

      - name: Create or update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.extract.outputs.version }}
          name: ${{ steps.extract.outputs.title }}
          body: ${{ steps.extract.outputs.body }}
          draft: false
          prerelease: ${{ steps.extract.outputs.prerelease == 'True' }}
          files: |
            DSL-KeyPad-${{ steps.extract.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
