name: Build & Release

on:
  push:
    branches:
      - main # или любая нужная ветка

jobs:
  build-and-release:
    runs-on: windows-latest

    permissions:
      contents: write # Нужна для создания/редактирования релизов

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run build script
        working-directory: ./src
        run: workflow.cmd
        shell: cmd

      - name: Set version environment variable
        run: |
          $version = Get-Content -Path src\version
          echo "version=$version" >> $GITHUB_ENV

      - name: Set prerelease environment variable
        run: |
          $prerelease = Get-Content -Path src\prerelease
          echo "prerelease=$prerelease" >> $GITHUB_ENV

      - name: Set message environment variable
        run: |
          $message = Get-Content -Path src\message
          echo "body=$message" >> $GITHUB_ENV

      - name: Delete existing ZIP asset (if any)
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.version }}
          assets: DSL-KeyPad-${{ env.version }}.zip

      - name: Create or update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.version }}
          name: ${{ env.version }}
          body: ${{ env.body }}
          draft: false
          prerelease: ${{ env.prerelease }}
          files: |
            DSL-KeyPad-${{ env.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
